// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    installedPlugins,
    pluginStorage,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (id = 1)',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cacheLimitMb =>
      columnsByName['cache_limit_mb']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cache_limit_mb',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestJson =>
      columnsByName['manifest_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get script =>
      columnsByName['script']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manifest_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'script',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'installed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plugin_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES installed_plugins(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    playbackSettings,
    installedPlugins,
    pluginStorage,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 playbackSettings = Shape4(
    source: i0.VersionedTable(
      entityName: 'playback_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get audioQuality =>
      columnsByName['audio_quality']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get audioFormatPriority =>
      columnsByName['audio_format_priority']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rememberPosition =>
      columnsByName['remember_position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tempPlayRewindSeconds =>
      columnsByName['temp_play_rewind_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get skipPreviewClips =>
      columnsByName['skip_preview_clips']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get outputDeviceId =>
      columnsByName['output_device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outputDeviceName =>
      columnsByName['output_device_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get restartRewindSeconds =>
      columnsByName['restart_rewind_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playHistoryLimit =>
      columnsByName['play_history_limit']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoScrollToCurrent =>
      columnsByName['auto_scroll_to_current']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audio_quality',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audio_format_priority',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remember_position',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (remember_position IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'temp_play_rewind_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'skip_preview_clips',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (skip_preview_clips IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'output_device_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'output_device_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'restart_rewind_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'play_history_limit',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_scroll_to_current',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (auto_scroll_to_current IN (0, 1))',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    playbackSettings,
    installedPlugins,
    pluginStorage,
    tracks,
    queueEntries,
    playerState,
    queueEntriesTrackKey,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 playbackSettings = Shape4(
    source: i0.VersionedTable(
      entityName: 'playback_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 tracks = Shape5(
    source: i0.VersionedTable(
      entityName: 'tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(track_key)'],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 queueEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'queue_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(position)'],
      columns: [_column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playerState = Shape7(
    source: i0.VersionedTable(
      entityName: 'player_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index queueEntriesTrackKey = i1.Index(
    'queue_entries_track_key',
    'CREATE INDEX queue_entries_track_key ON queue_entries (track_key)',
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackKey =>
      columnsByName['track_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceTypeId =>
      columnsByName['source_type_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cid =>
      columnsByName['cid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploader =>
      columnsByName['uploader']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get artworkJson =>
      columnsByName['artwork_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_type_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cid',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uploader',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'artwork_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get trackKey =>
      columnsByName['track_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get shuffleRank =>
      columnsByName['shuffle_rank']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES tracks(track_key)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'shuffle_rank',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get currentPosition =>
      columnsByName['current_position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get positionMs =>
      columnsByName['position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get loopMode =>
      columnsByName['loop_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get shuffleEnabled =>
      columnsByName['shuffle_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get volume =>
      columnsByName['volume']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get muted =>
      columnsByName['muted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'current_position',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'loop_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'shuffle_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (shuffle_enabled IN (0, 1))',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'volume',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'muted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (muted IN (0, 1))',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    playbackSettings,
    installedPlugins,
    pluginStorage,
    tracks,
    queueEntries,
    playerState,
    playHistory,
    queueEntriesTrackKey,
    playHistoryPlayedAt,
    playHistoryTrackKey,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 playbackSettings = Shape4(
    source: i0.VersionedTable(
      entityName: 'playback_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 tracks = Shape5(
    source: i0.VersionedTable(
      entityName: 'tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(track_key)'],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 queueEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'queue_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(position)'],
      columns: [_column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playerState = Shape7(
    source: i0.VersionedTable(
      entityName: 'player_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 playHistory = Shape8(
    source: i0.VersionedTable(
      entityName: 'play_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_40, _column_32, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index queueEntriesTrackKey = i1.Index(
    'queue_entries_track_key',
    'CREATE INDEX queue_entries_track_key ON queue_entries (track_key)',
  );
  final i1.Index playHistoryPlayedAt = i1.Index(
    'play_history_played_at',
    'CREATE INDEX play_history_played_at ON play_history (played_at)',
  );
  final i1.Index playHistoryTrackKey = i1.Index(
    'play_history_track_key',
    'CREATE INDEX play_history_track_key ON play_history (track_key)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get trackKey =>
      columnsByName['track_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get playedAt =>
      columnsByName['played_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'played_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    playbackSettings,
    installedPlugins,
    pluginStorage,
    tracks,
    queueEntries,
    playerState,
    playHistory,
    layoutState,
    queueEntriesTrackKey,
    playHistoryPlayedAt,
    playHistoryTrackKey,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 playbackSettings = Shape4(
    source: i0.VersionedTable(
      entityName: 'playback_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 tracks = Shape5(
    source: i0.VersionedTable(
      entityName: 'tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(track_key)'],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 queueEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'queue_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(position)'],
      columns: [_column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playerState = Shape7(
    source: i0.VersionedTable(
      entityName: 'player_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 playHistory = Shape8(
    source: i0.VersionedTable(
      entityName: 'play_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_40, _column_32, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 layoutState = Shape9(
    source: i0.VersionedTable(
      entityName: 'layout_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_42, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index queueEntriesTrackKey = i1.Index(
    'queue_entries_track_key',
    'CREATE INDEX queue_entries_track_key ON queue_entries (track_key)',
  );
  final i1.Index playHistoryPlayedAt = i1.Index(
    'play_history_played_at',
    'CREATE INDEX play_history_played_at ON play_history (played_at)',
  );
  final i1.Index playHistoryTrackKey = i1.Index(
    'play_history_track_key',
    'CREATE INDEX play_history_track_key ON play_history (track_key)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get playerTab =>
      columnsByName['player_tab']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get panelExpanded =>
      columnsByName['panel_expanded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get panelWidth =>
      columnsByName['panel_width']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'player_tab',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'panel_expanded',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (panel_expanded IN (0, 1))',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'panel_width',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL CHECK (panel_width <= 1600.0)',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    playbackSettings,
    installedPlugins,
    pluginIndexes,
    pluginStorage,
    tracks,
    queueEntries,
    playerState,
    playHistory,
    layoutState,
    queueEntriesTrackKey,
    playHistoryPlayedAt,
    playHistoryTrackKey,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 playbackSettings = Shape4(
    source: i0.VersionedTable(
      entityName: 'playback_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 installedPlugins = Shape10(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 pluginIndexes = Shape11(
    source: i0.VersionedTable(
      entityName: 'plugin_indexes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(url)'],
      columns: [_column_48, _column_49],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 tracks = Shape5(
    source: i0.VersionedTable(
      entityName: 'tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(track_key)'],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 queueEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'queue_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(position)'],
      columns: [_column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playerState = Shape7(
    source: i0.VersionedTable(
      entityName: 'player_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 playHistory = Shape8(
    source: i0.VersionedTable(
      entityName: 'play_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_40, _column_32, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 layoutState = Shape9(
    source: i0.VersionedTable(
      entityName: 'layout_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_42, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index queueEntriesTrackKey = i1.Index(
    'queue_entries_track_key',
    'CREATE INDEX queue_entries_track_key ON queue_entries (track_key)',
  );
  final i1.Index playHistoryPlayedAt = i1.Index(
    'play_history_played_at',
    'CREATE INDEX play_history_played_at ON play_history (played_at)',
  );
  final i1.Index playHistoryTrackKey = i1.Index(
    'play_history_track_key',
    'CREATE INDEX play_history_track_key ON play_history (track_key)',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestJson =>
      columnsByName['manifest_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get script =>
      columnsByName['script']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceIndexUrl =>
      columnsByName['source_index_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checksJson =>
      columnsByName['checks_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_index_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'checks_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
  ),
);
