// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    installedPlugins,
    pluginStorage,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (id = 1)',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cacheLimitMb =>
      columnsByName['cache_limit_mb']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cache_limit_mb',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestJson =>
      columnsByName['manifest_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get script =>
      columnsByName['script']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manifest_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'script',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'installed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plugin_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES installed_plugins(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appearanceSettings,
    networkSettings,
    playbackSettings,
    installedPlugins,
    pluginStorage,
  ];
  late final Shape0 appearanceSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'appearance_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 networkSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'network_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 playbackSettings = Shape4(
    source: i0.VersionedTable(
      entityName: 'playback_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPlugins = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_plugins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pluginStorage = Shape3(
    source: i0.VersionedTable(
      entityName: 'plugin_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, "key")'],
      columns: [_column_9, _column_10, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get audioQuality =>
      columnsByName['audio_quality']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get audioFormatPriority =>
      columnsByName['audio_format_priority']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rememberPosition =>
      columnsByName['remember_position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tempPlayRewindSeconds =>
      columnsByName['temp_play_rewind_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get skipPreviewClips =>
      columnsByName['skip_preview_clips']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get outputDeviceId =>
      columnsByName['output_device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outputDeviceName =>
      columnsByName['output_device_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get restartRewindSeconds =>
      columnsByName['restart_rewind_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playHistoryLimit =>
      columnsByName['play_history_limit']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoScrollToCurrent =>
      columnsByName['auto_scroll_to_current']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audio_quality',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audio_format_priority',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remember_position',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (remember_position IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'temp_play_rewind_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'skip_preview_clips',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (skip_preview_clips IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'output_device_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'output_device_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'restart_rewind_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'play_history_limit',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_scroll_to_current',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (auto_scroll_to_current IN (0, 1))',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
